// frontend/src/components/VideoCard.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
import type { VideoItem } from '@/types/video'
import { formatViews, timeAgo } from '@/services/mock-videos'
import AppIcon from '@/components/icons/AppIcon.vue'

defineProps<{ video: VideoItem }>()
</script>

<template>
  <RouterLink :to="`/video/${video.id}`" class="video-card">
    <div class="thumb-wrap">
      <img :src="video.thumbnail" :alt="video.title" class="thumb" />
      <span class="duration">{{ video.duration }}</span>
    </div>

    <div class="meta">
      <img :src="video.authorAvatar" :alt="video.authorName" class="avatar" />
      <div class="meta-text">
        <h3>{{ video.title }}</h3>
        <p class="author">{{ video.authorName }}</p>
        <p class="sub">
          <span><AppIcon name="views" :size="13" /> {{ formatViews(video.views) }} views</span>
          <span>•</span>
          <span><AppIcon name="clock" :size="13" /> {{ timeAgo(video.uploadDate) }}</span>
        </p>
      </div>
    </div>
  </RouterLink>
</template>

<style scoped>
.video-card {
  display: grid;
  gap: 10px;
  text-decoration: none;
}

.thumb-wrap {
  position: relative;
  aspect-ratio: 16 / 9;
  border-radius: 14px;
  overflow: hidden;
  background: #1f1f1f;
}

.thumb {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: transform 180ms ease;
}

.video-card:hover .thumb {
  transform: scale(1.03);
}

.duration {
  position: absolute;
  right: 8px;
  bottom: 8px;
  font-size: 12px;
  padding: 2px 6px;
  border-radius: 6px;
  color: #fff;
  background: rgba(0, 0, 0, 0.72);
}

.meta {
  display: grid;
  grid-template-columns: 38px 1fr;
  gap: 10px;
}

.avatar {
  width: 38px;
  height: 38px;
  border-radius: 999px;
  object-fit: cover;
}

.meta-text h3 {
  color: #f3f4f6;
  font-size: 14px;
  line-height: 1.3;
  margin-bottom: 2px;
}

.author {
  color: #c1c5ce;
  font-size: 13px;
}

.sub {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  color: #9ca3af;
  font-size: 12px;
}

.sub span {
  display: inline-flex;
  align-items: center;
  gap: 3px;
}
</style>

// UI/src/app/components/video-card.tsx
import { Link } from "react-router";
import { Video } from "../data/mock-data";
import { Eye, Clock } from "lucide-react";

interface VideoCardProps {
  video: Video;
}

export function VideoCard({ video }: VideoCardProps) {
  const formatViews = (views: number) => {
    if (views >= 1000000) {
      return `${(views / 1000000).toFixed(1)}M`;
    } else if (views >= 1000) {
      return `${(views / 1000).toFixed(1)}K`;
    }
    return views.toString();
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    const now = new Date();
    const diffTime = Math.abs(now.getTime() - date.getTime());
    const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
    
    if (diffDays === 0) return 'Today';
    if (diffDays === 1) return 'Yesterday';
    if (diffDays < 7) return `${diffDays} days ago`;
    if (diffDays < 30) return `${Math.floor(diffDays / 7)} weeks ago`;
    if (diffDays < 365) return `${Math.floor(diffDays / 30)} months ago`;
    return `${Math.floor(diffDays / 365)} years ago`;
  };

  return (
    <Link to={`/video/${video.id}`} className="group">
      <div className="space-y-3">
        {/* Thumbnail */}
        <div className="relative aspect-video rounded-xl overflow-hidden bg-[#282828]">
          <img
            src={video.thumbnail}
            alt={video.title}
            className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
          />
          <div className="absolute bottom-2 right-2 bg-black/80 text-white text-xs px-2 py-1 rounded">
            {video.duration}
          </div>
        </div>

        {/* Info */}
        <div className="flex gap-3">
          <img
            src={video.authorAvatar}
            alt={video.authorName}
            className="w-9 h-9 rounded-full shrink-0"
          />
          <div className="flex-1 min-w-0">
            <h3 className="text-white font-medium line-clamp-2 group-hover:text-gray-300 transition-colors">
              {video.title}
            </h3>
            <p className="text-sm text-gray-400 mt-1">{video.authorName}</p>
            <div className="flex items-center gap-2 text-xs text-gray-400 mt-1">
              <span className="flex items-center gap-1">
                <Eye className="w-3 h-3" />
                {formatViews(video.views)} views
              </span>
              <span>•</span>
              <span>{formatDate(video.uploadDate)}</span>
            </div>
          </div>
        </div>
      </div>
    </Link>
  );
}
